export enum ReviewStatus {
  QUEUED = 'QUEUED',
  FETCHING = 'FETCHING',
  ANALYZING = 'ANALYZING',
  AI_REVIEW = 'AI_REVIEW',
  AGGREGATING = 'AGGREGATING',
  PUBLISHING = 'PUBLISHING',
  COMPLETED = 'COMPLETED',
  PARTIAL = 'PARTIAL',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum Severity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

export enum FindingCategory {
  BUG = 'BUG',
  SECURITY = 'SECURITY',
  PERFORMANCE = 'PERFORMANCE',
  MAINTAINABILITY = 'MAINTAINABILITY',
  READABILITY = 'READABILITY',
  ERROR_HANDLING = 'ERROR_HANDLING',
  EDGE_CASE = 'EDGE_CASE',
  API_MISUSE = 'API_MISUSE',
  CONCURRENCY = 'CONCURRENCY',
  DATABASE = 'DATABASE',
  REACT = 'REACT',
  NODEJS = 'NODEJS',
  TYPESCRIPT = 'TYPESCRIPT',
  TEST_GAP = 'TEST_GAP',
  STYLE = 'STYLE',
}

export enum JobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum AnalyzerType {
  ESLINT = 'ESLINT',
  TYPESCRIPT = 'TYPESCRIPT',
  AI = 'AI',
  SECURITY = 'SECURITY',
  CUSTOM = 'CUSTOM',
}

export enum RegressionStatus {
  NOT_RUN = 'NOT_RUN',
  PASS = 'PASS',
  WARN = 'WARN',
  FAIL = 'FAIL',
  ERROR = 'ERROR',
}

